version: '3.8'
services:
  mysql-db:
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    ports:
      - '6033:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: url_shortner_db
    volumes:
      - mysql-dbdata:/var/lib/mysql

volumes:
  mysql-dbdata:
    driver: local
